webApp/__init__.py
from flask import Flask
from webApp.config import Config
from webApp.functions import build_terminal

app = Flask(__name__)
app.config.from_object(Config)

from webApp.pages.errors.handlers import errors_bp # Error pages
app.register_blueprint(errors_bp)
from webApp.pages.home.routes import home_bp  # Add Homepage
app.register_blueprint(home_bp)
from webApp.pages.timeline.routes import timeline_bp # Add About page
app.register_blueprint(timeline_bp)
from webApp.pages.projects.routes import projects_bp # Add Projects page
app.register_blueprint(projects_bp)
from webApp.pages.projects.routes import project_bp # Add Project page
app.register_blueprint(project_bp)
from webApp.pages.about.routes import about_bp # Add About page
app.register_blueprint(about_bp)


if __name__ == '__main__':
    print("building terminal.js")
    build_terminal("./static/js")
    print("running py app")
    app.run(host="127.0.0.1", port=5000, debug=True)

webApp/pages/about/routes.py
from flask import Blueprint, render_template
from webApp.functions import get_static_json
import json

about_bp = Blueprint('about', __name__, template_folder='html')


@about_bp.route('/about.html')
def landing():
    # General about page info
    data_about = get_static_json('about.json')

    # Query for Projects
    if "projects" in data_about:
        data_project = get_static_json('projects.json')['projects']
        project_list = data_about['projects']

        for i in range(len(data_project) - 1, -1, -1):
            if data_project[i]['name'] not in project_list:
                data_project.pop(i)

    else:
        data_project = None

    return render_template('landing_about.html', projects=data_project, about=data_about)


def order_projects_by_weight(projects):
    try:
        return int(projects['weight'])
    except KeyError:
        return 0

webApp/pages/home/routes.py
from flask import Blueprint, render_template
from webApp.functions import get_static_json

home_bp = Blueprint('home', __name__, template_folder='html')

@home_bp.route('/')
@home_bp.route('/home.html')
def landing():
    about = get_static_json('about.json')
    terminal = get_static_json('terminal.json')
    return render_template('landing_home.html', about=about, terminal=terminal)

webApp/pages/projects/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, abort
from webApp.functions import get_static_json

projects_bp = Blueprint('projects', __name__, template_folder='html')
project_bp = Blueprint('project', __name__, template_folder='html')


@projects_bp.route('/projects.html')
def landing():
    data = get_static_json('projects.json')['projects']
    data.sort(key=order_projects_by_date)

    tags = request.args.get('tags')

    if tags:
        tags = tags.split(',')
        data = [project for project in data if set(tags) <= set(project['tags'])]

    return render_template('landing_projects.html', projects=data, tags=tags)


@project_bp.route('/projects/<title>.html')
def project(title):
    projects = get_static_json('projects.json')['projects']
    project = next((project for project in projects if project['link'] == title), None)

    if project is None:  # Project doesn't exists
        abort(404)
    if project['long'] == "" or project['long'] is None:  # Project page is under construction
        abort(501)
    else:
        return render_template('project.html', project=project)


def order_projects_by_weight(projects):
    try:
        return int(projects['weight'])
    except KeyError:
        return 0


def order_projects_by_date(project):
    if 'date' not in project:
        status = 0
    else:
        status = 1

    try:
        date = -int(datetime.strptime(project['date'], "%b %Y").strftime("%Y%m%d"))
    except KeyError:
        date = 0
    except ValueError:
        date = 0

    output = (status, date)

    return output

webApp/pages/timeline/routes.py
from flask import Blueprint, render_template
import json, os
from webApp.functions import get_static_json

timeline_bp = Blueprint('timeline', __name__, template_folder='html')

@timeline_bp.route('/timeline.html')
def landing():
    data = get_static_json('timeline.json')['years']
    return render_template('landing_timeline.html', years=data)

webApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:900" rel="stylesheet">


    <title>Joshua de Jong</title>
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon/favicon.ico') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon/favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='images/favicon/site.webmanifest') }}">
    <link rel="mask-icon" color="#da532c" href="{{ url_for('static', filename='images/favicon/safari-pinned-tab.svg') }}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    {% block base_head %}
    {% endblock %}
</head>
<body>
    <dev class="navbar-ul">
            <ul id="navbar-list" class="list-inline">
                <li><a class="navbar-ref" href="{{ url_for('home.landing') }}">Home</a></li>
                <li><a class="navbar-ref" href="{{ url_for('projects.landing') }}">Projects</a></li>
                <li><a class="navbar-ref" href="{{ url_for('timeline.landing') }}">Timeline</a></li>
                <li><a class="navbar-ref" href="{{ url_for('about.landing') }}">About</a></li>
            </ul>
    </dev>

    {% block base_body %}
    {% endblock %}

</body>
</html>

webApp/templates/card.html
<head>
</head>

<body>
    <!-- Modal -->
    <div id="modal-{{ project['name'] }}" class="modal modal-window">
        <div class="flex-window">
            <div class="modal-padding modal-action modal-close"></div>
            <div class="modal-background">
                    <!-- Close Button -->
                    <a class="modal-action modal-close modal-quit-button btn-floating btn-small waves-effect waves-light">
                        <i class="material-icons">
                            close
                        </i>
                    </a>

                    <!-- Modal Header -->
                    <div class="modal-header row no-margin-bottom">
                        <!-- Project Icon -->
                        <div class="col col-icon">
                            <div class="icon-container">
                                <img class="icon-image" src={{project['icon']}}>
                            </div>
                        </div>

                        <!-- Project Title & Tags -->
                        <div class="col col-title">
                            <div class="center-if-small title-margin">
                                <span class="modal-title">
                                    {{ project['name'] }}
                                </span>
                                {% if 'tags' in project %}
                                    <div class="md-chips container-inner" style="overflow-x: hidden;">
                                        {% for tag in project['tags'] %}
                                        <div class="md-chip md-chip-clickable">
                                            <a class="md-chip-link" href="{{ url_for('projects.landing', tags=tag) }}">
                                                {{tag}}
                                            </a>
                                        </div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                {% if 'github' in project %}
                                    <div style="margin-top: 8px;">
                                        <span class="media-box">
                                            <a target="_blank" href={{project['github']}}>
                                                <img class="media-logo" src="static/images/github.svg">
                                            </a>
                                            Github
                                        </span>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <!-- Modal Content -->
                    <div class="modal-content">
                        <!-- Custom Layout -->
                        {% if 'html' in project %}
                            {% include project['html'] %}
                        <!-- Auto Content -->
                        {% else %}
                            <!-- Project Description -->
                            {% if 'long' in project %}
                                {% for par in project['long'] %}
                                    <p>{{par|safe}}</p>
                                {% endfor %}
                            {% endif %}
                        {% endif %}

                        <!-- Project Photos -->

                        <!-- Skills & Tech -->

                    </div>

                    <!-- Modal Footer -->
                    <div class="modal-footer">
                        <hr class="hr-one">
                        <span>
                            {% if 'date' in project %}
                                <a class="status">Released: {{project['date']}}</a>
                            {% else %}
                                <a class="status">Work in Progress</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            <div class="modal-padding modal-action modal-close"></div>
            <div class="modal-padding-extra modal-action modal-close"></div>
        </div>
    </div>

    <!-- Card -->
    <div class="col s12 m6 l4">
        <div class="card hoverable project">
            <!-- Project Icon -->
            <div class="card-image waves-effect waves-block waves-light activator">
                {% if 'icon' in project %}
                    <img class="card-image activator" src={{project['icon']}}>
                {% else %}
                    <img class="card-image activator" src="/static/images/dev.jpg">
                {% endif %}
            </div>

            <!-- Card Content -->
            <div class="card-content activator">
                <!-- Project Name -->
                <span id="title" class="no-margin-bottom card-title activator grey-text text-darken-4" title="{{project['name']}}">
                    {{project['name']}}
                </span>
                <!-- Tags -->
                {% if 'tags' in project %}
                    <div class="container-outer">
                        <div class="md-chips container-inner">
                            {% for tag in project['tags'] %}
                            <div class="md-chip md-chip-clickable">
                                <a class="md-chip-link" href="{{ url_for('projects.landing', tags=tag) }}">
                                    {{tag}}
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                <div class="row no-margin-bottom">
                    <!-- Read More -->
                    <div class="col col-reveal-title">
                        {% if ('long' in project) or ('html' in project) %}
                            <span><a class="modal-trigger" href="#modal-{{ project['name'] }}">Read More</a></span>
                        {% endif %}
                        {% if (('long' in project) or ('html' in project)) and ('github' in project) %}
                            <span> | </span>
                        {% endif %}
                        {% if 'github' in project %}
                            <span><a class="github" href={{project['github']}}>Github</a></span>
                        {% endif %}
                    </div>

                    <!-- show more -->
                    <div class="col col-reveal-icon">
                        {% if 'short' in project %}
                            <span>
                                <i class="material-icons right activator">more_vert</i>
                            </span>
                        {% endif %}
                    </div>
                </div>

            </div>

            <!-- Card Reveal -->
            {% if 'short' in project %}
                <div class="card-reveal">
                    <div class="row no-margin-top no-margin-bottom">
                        <div class="col col-reveal-title">
                            <span class="card-title grey-text text-darken-4">{{project['name']}}</span>
                        </div>
                        <div class="col col-reveal-icon">
                            <span class="card-title activator" style="display: contents;"><i class="material-icons right vcenter-close">close</i></span>
                        </div>
                    </div>
                    {% if 'date' in project %}
                        <div><span class="status">{{project['date']}}</span></div>
                    {% else %}
                        <div><span class="status">Work in Progress</span></div>
                    {% endif %}
                    <p>{{project['short']}}</p>

                    <div class="bottom-aligned">
                        {% if ('long' in project) or ('html' in project) %}
                            <span><a class="modal-trigger" href="#modal-{{ project['name'] }}">Read More</a></span>
                        {% endif %}
                        {% if (('long' in project) or ('html' in project)) and ('github' in project) %}
                            <span> | </span>
                        {% endif %}
                        {% if 'github' in project %}
                            <span><a class="github" href={{project['github']}}>Github</a></span>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</body>

webApp/templates/project_pages/blackjack.html
<p>
    As I have always been fascinated with blackjack and always wanted to create a terminal game I thought I would kill two birds with one stone.
    The game includes a betting system, an automated dealer, assci art, and the standard set of blackjack rules.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/blackjack/Bet.png">
</div>

webApp/templates/project_pages/edct.html
<p>
    A toolset created in Matlab to aid in empirical data collection of vapor-to-particle reactions for a chemistry lab at Colorado State University.
    The tool set consists of four main programs these being:
</p>
<ul>
    <li>
        <b>ColorSpec</b>
        -
        Analysis the RGB values of an image or video in a given region.
        The user can specify to break the region into vertical or horizontal slices for further analysis.
    </li>
    <li>
        <b>LineSpec</b>
        -
        Analyzes the color intensity and light intensity of an image or video on a given line.
    </li>
    <li>
        <b>Crystal Analysis</b>
        -
        Maps regions of a particle or material to show the underlying crystal structure through the use of a 2d fourier transform.
        If the region consists of only noise or no substantial phase cannot be found, the region is further broken up regions and analysed.
    </li>
    <li>
        <b>TornadoPulse</b>
        -
        Analyzes the changing volume and perimeter of a particle cloud.
        This allows the user to measure the volume of the vortex rings leaving the vapor-to-particle site as well as the frequency.
    </li>
</ul>

<h5>Color Spec</h5>
<p>
    The user provides a photo or video to be analysed using a gui.
    Once the media is loaded into memory the user then selects a region of the media.
    The RGB values from the media is then analyzed as a histogram and then vertical cross sections.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/ColorSpec_RegionSelect.png">
</div>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/ColorSpec_Histogram.png">
</div>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/ColorSpec_CrossSections.png">
</div>

<h5>Line Spec</h5>
<p>
    The user loads in a photo or video and draws a pixel thin line on the media.
    The pixels across the user's line are then analyzed per a frame and produces live data.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/SpecLine_region.png">
</div>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/LineSpec_Data.png">
</div>

<h5>Crystal Analysis</h5>
<p>
    The user provides an image from Digital Microscope (dm3).
    The image is recursively broken up into regions to fit within the edges of the detected particle.
    Each region then undergoes a 2d fourier transform to detect the orientation of crystalline structure with in the region.
    Regions are then grouped together using a K clustering algorithm and colored according to its grouping.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/CryAnalysis_Material.png">
</div>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/CryAnalysis_Orientations.png">
</div>

<h5>Tornado Pulse</h5>
<p>
    This application looks as the light intensity from a video and identifies a blob using standard deviations.
    The area, center and perimeter of the blob are recorded over time, blobs whose center is outside of the blue bounding box are ignored.
    The tool allows the user to measure the rate at which the aerosol leaves the droplet.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/TornadoPulse_Sample.png">
</div>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vapor-to-particle-reaction/TornadoPulse_MachineVision.png">
</div>

webApp/templates/project_pages/grind.html
<p>
    A Counter Strike: Global Offensive bomb defusal map set in Namibia mine.
    Featuring a highly competitive layout focused around map control, and 100% custom environment art.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/grind/truck.jpg">
</div>

<h5>History</h5>
<p>
    I original started the de_grind as a passion project to reinvent de_dust, a classic Counter Strike map which has fallen out of popularity.
    While very little of de_dust exists in the final version of de_grind the competitive feel and the art style, albeit more industrial, carried over into de_grind.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/grind/bsite.jpg">
</div>

<p>
    Over the course of 2 years the project took a lot of different directions, styles, and concepts before reaching its finished state.
    Early on the map went through many themes; an sandy North Africa theme, then a small coastal Italian village, and then through a modern condo theme.
    During this time I grew rapidly as a level designer and more proficient with the toolset.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/grind/outside.jpg">
</div>

<p>
    I eventually joined Mapcore, a level design community, where I meet Jan Huygelen.
    Together we worked on polishing the gameplay and trying to pin down a theme.
    Unfortunately, before we could pin down a theme and finish the map Jan got a offer to work on a high profile project, de_mirage2 later called de_thrill.
    While working with Jan, I learned the depths of the source engine and developed my skill set as an artist.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/grind/underground.jpg">
</div>

<p>
    As I was committed to finish the project and did not have the skill set to finish the project on my own, I sought after a new team member.
    I eventually recruited Konstantin Loffler, another level designer, to finalize the gameplay of the map.
    Together we extensively playtested the map and settled on the final theme, a modern mining facility.
<p>
    We then recruited Cory de la Torre to act as our lead Environment Artist.
    With his help we finished the art and shipped with 100% self generated art content.
</p>

webApp/templates/project_pages/notakto.html
<p>
    Notakto is a variant of tic-tac-toe which can be played across one or several boards.
    Both players use the same piece, an "X", with the goal of forcing the opponent to make a three-in-a-row of Xs.
    The game is traditional played on a 3x3 board, however any NxM board is possible where N,M >= 3.
    The game has a distinct advantage over tic-tac-toe as there will always be a winner, however the winner is often determined by who went first and the size of the board.
</p>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/notakto/Title.png">
</div>

<p>
    The game includes different choices of board size, a player verse player mode, and three different levels of AI to play against.
    The AI play the game as following:
</p>
<ul class="ul-bullets">
    <li>
        <b>Easy:</b> Make a random move into an unoccupied square.
    </li>
    <li>
        <b>Medium:</b> Make a random move into an unoccupied square which will not result in an immediate loss.
    </li>
    <li>
        <b>Hard:</b> Make an optimal move into an unoccupied square which will not result in an immediate loss and maximizes the chance of winning next turn.
        Look ahead by one turn.
    </li>
</ul>

<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/notakto/Last Turn.png">
</div>

webApp/templates/project_pages/portfolio.html
<p>
    If you are reading this then you most likely are viewing the live project!
    I built this portfolio as a way to host my project, share a bit about me and learn some frontend development.
</p>

<p>
    Here are the key features of this project!
</p>

<ul class="ul-bullets">
    <li>A fully reactive layout friendly for desktop, Iphone, and Android.</li>
    <li>A modern sleek design to show off you and your projects.</li>
    <li>An easy way to maintain and update the portfolio without knowing HTML, CSS, or JS. You only need to know Json, and Python!</li>
    <li>Dynamic page layouts to match your content - no need to fight the layout.</li>
    <li>Awesome animations to prevent your skills from just being plain text. </li>
</ul>

<p>For more details on this project visit the github repo.</p>

webApp/templates/project_pages/seattle-fire.html
<p>
    <b>Note:</b> This project is a work in progress and is not complete.
    In the close future I hope to host the application on the web for others to use!
</p>


<h5>Goal</h5>
<p>
    I have always enjoyed seeing what the Seattle Fire Department is doing through out the day.
    However, while I can view the department's activity on their <a href="http://www2.seattle.gov/fire/realtime911/getRecsForDatePub.asp?action=Today&incDate=&rad1=des">website</a> I always wondered the following:
    <ul class="ul-bullets">
        <li>Where is that incident in relation to where I am?</li>
        <li>What does do the emergency code mean?</li>
        <li>How and where can I learn more about a large event?</li>
        <li>What do the vehicle codes mean and what do the vehicles look like?</li>
        <li>How common are these types of incidents?</li>
        <li>How long does it take for the department to arrive to an incident and how long are they there?</li>
    </ul>
    With this project I hope to create an easy way for people to learn and share info about incidents in the Seattle area.
</p>
<p>
    Another large driving force for this project is building my skills as a fullstack developer and learning more about starting a business.
</p>



<h5>Images</h5>
<div class="row">
    <div class="col s6 m4 l4">
            <img class="article-img" src="/static/images/projects/seattle-fire-dispatch/image_1.png">
    </div>
    <div class="col s6 m4 l4">
            <img class="article-img" src="/static/images/projects/seattle-fire-dispatch/image_2.png">
    </div>
    <div class="col s6 m4 l4">
            <img class="article-img" src="/static/images/projects/seattle-fire-dispatch/image_3.png">
    </div>
</div>

<h5>Stack</h5>
<ul class="ul-bullets">
    <li>
        <b>Frontend:</b> Flask, Javascript, Html, CSS, Sass, Mapbox
    </li>
    <li>
        <b>Database:</b> Postgres, Redis
    </li>
    <li>
        <b>Backend:</b> Python
    </li>
</ul>

webApp/templates/project_pages/vending_machine.html
<p>
    During an interview I was asked a whiteboard question to design a vending machine in C.
    After the interview I took the time to implement my solution and identify design issues.
</p>
<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/vending-machine/Purchase.png">
</div>
<p>
    The program generates a random inventory from a list of possible snacks, sets a price, and a random quantity.
    The inventory is then displayed to the user in the terminal.
    The user is then able to select a item from the vending machine and choices how much they want to pay.
    If the user pays enough money for the snack, the machine dispenses the snack and change.
</p>

webApp/templates/project_pages/voronoi.html
<h5>What are Voronoi Diagrams?</h5>
<p>
    A voronoi diagram is a partitioning of a plane with n generating points into convex polygons such that each polygon contains exactly one generating point and every point in a given polygon is closer to its generating point than any other point.
    They are also known as Voronoi tessellation, Voronoi decomposition, Voronoi Partition, or Dirichlet tessellation.
</p>

<h5>Creating Art</h5>
<p>
    Using a Voronoi Diagram we can create mosaic or plainting like repersentations of an original image. To do this we use the following algorithm:
</p>

<ul class="ul-bullets">
    <li>
        Given an image I, generate a random set of n points P which lies within the perimeter of I.
    </li>
    <li>
        Generate a Voronoi Diagram V from the set of points P. Let v_i denote a polygon in V.
    </li>
    <li>
        Color each polygon v_i using the pixel valaue from I located at the center of v_i.
    </li>
    <li>
        If a polygon v_i center is not located on I, color v_i using the pixel value from the closest point on I to the center of v_i.
    </li>
</ul>

<p>
    While using the algorithm the final image can vastly differ depending on your set of points P.
    For instance, if you generate your set P using a Gaussian distribution, increasing the amount of points n improves the clarity of the final image.
    While using a skewed distribution to create P can make a sense of depth or focus to the final image.
</p>

<h5>Raw Image</h5>
<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/voronoi/Land_1.jpg">
</div>

<h5>Voronoi Representation</h5>
<div class="article-img-container">
    <img class="article-img" src="/static/images/projects/voronoi/Land_1_Final.png">
</div>